name: Deploy to test host
on:
  workflow_dispatch:
  push:
      branches:
        - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push to hub
        run: |
          docker build -t syryx/speakid-frontend:test .
          docker push syryx/speakid-frontend:test

  deploy-to-test-host:
    needs: build
    name: Deploy to test host
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run on host
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.TEST_HOST }}
          port: ${{ vars.TEST_PORT || 22 }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_PRIVATE_KEY }}
#          fingerprint: ${{ vars.TEST_FINGERPRINT }}
          script: |
            docker pull syryx/speakid-frontend:test
            docker stop speakid_frontend || true
            docker rm speakid_frontend || true
            docker run -d --name speakid_frontend -p 8081:80 syryx/speakid-frontend:test
