name: Deploy to test host
on:
  push:
      branches:
        - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: echo
        run: echo ${{ vars.DOCKERHUB_USERNAME }}

      - name: Login to hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ vars.DOCKERHUB_PASSWORD }}

      - name: Build and push to hub
        run: |
          docker build -t syryx/speakid-frontend:test .
          docker push syryx/speakid-frontend:test

  deploy-to-test-host:
    needs: build
    name: Deploy to test host
    runs-on: ubuntu-latest
    steps:
      - name: Pull and run on host
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{ vars.TEST_HOST }}
          port: ${{ vars.TEST_PORT || 22 }}
          user: ${{ vars.TEST_USERNAME }}
          private_key: ${{ vars.TEST_PRIVATE_KEY }}
          command: |
            docker pull syryx/speakid-frontend:test
            docker stop speakid_frontend || true
            docker rm speakid_frontend || true
            docker run -d --name speakid_frontend -p 8081:80 syryx/speakid-frontend:test
